# .travis.yml     Travis CI configuration file for MindForger
#
# Copyright (C) 2014-2020  Martin Dvorak <martin.dvorak@mindforger.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

os:
  - linux
  
# Missing codecvt: upgrade from g++ 4.8 to 5 > MATRIX_EVAL sets CXX to g++-5 > qmake CONFIG and QMAKE_CXX sets it to build process
matrix:
  include:
    - os: linux
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5" # IMPROVE prepend ccache to speed up 2nd build (MF after units)

language: cpp # see https://docs.travis-ci.com/user/languages/cpp/
compiler:
  - gcc # Travis CI defines CXX=g++ env var
sudo: required
dist: trusty # Travis CI provides Precise and Trusty only

before_install:
  - sudo apt-get update -qq
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"  
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - eval "${MATRIX_EVAL}"

install:
  - sudo apt-get install -qq qtbase5-dev libqt5webkit5-dev
  - sudo apt-get install -qq qt5-default qttools5-dev-tools
  - sudo apt-get install -qq ccache
  - sudo apt-get install -qq libgtest-dev
  - "export M8RHOME=`pwd`"
  - cd /usr/src/gtest # I have to build Google Test Framework myself
  - sudo apt-get install -qq cmake
  - sudo cmake .
  - sudo make
  - sudo mv libg* /usr/lib/

script: # make lib unit tests > run lib unit tests > make MF > install MF
  - cd "${M8RHOME}"
  - eval "${MATRIX_EVAL}"
  - cd deps/cmark-gfm && mkdir -v build && cd build && cmake -DCMARK_TESTS=OFF -DCMARK_SHARED=OFF .. && cmake --build . && cd ../../..
  - "echo \"M8RDEBUG: g++ compiler is set to: ${CXX}\""  
  # - cd lib/test # UNIT tests
  # - qmake -r CONFIG+=mfnocxx CONFIG+=mfunits QMAKE_CXX=${CXX} mindforger-lib-unit-tests.pro
  # - make
  # - cd src && export M8R_GIT_PATH="${M8RHOME}" && ./mindforger-lib-unit-tests > /tmp/mindforger-unit-tests.log 2>&1 # ; true
  # - cd ../../..
  # - cat /tmp/mindforger-unit-tests.log
  - qmake -r CONFIG+=mfnocxx QMAKE_CXX=${CXX} qt_test.pro
  - make
  - sudo make install
